---
- name: Install, configured and join Linux to Microsoft Active Directory
  hosts: all
  become: yes
 
  tasks:
  - name: Disable i386 architecture
    command: dpkg --remove-architecture i386
 
  - name: Install SSSD, KRB5, ADCLI, SAMBA, WINBIND, USBGUARD, CIFS packages and dependenses 
    apt: 
      name={{ item }} state=latest 
    loop:
      - krb5-user
      - samba
      - winbind
      - libpam-krb5
      - libpam-winbind
      - libnss-winbind
      - sssd-tools  
      - oddjob
      - msktutil
      - net-tools
      - adcli
      - realmd
      - linphone
      - tree
      - sharutils
      - usbguard
      - kmplayer
      - default-jdk
      - default-jre
      - openjdk-8-jre-headless
      - openjdk-8-jdk-headless
      - ubuntu-restricted-extras
      - gnome-panel
      - cifs-utils
      - keyutils
      - synaptic
      - libpam-ccreds 
  
  - name: Creating Kerberos configuration
    template:
      src: "templates/krb5.conf.j2"
      dest: "/etc/krb5.conf"
      mode: 0755
      
  - name: Creating SSSD configuration
    template:
      src: "templates/sssd.conf.j2"
      dest: "/etc/sssd/sssd.conf"
      mode: 0755
      
  - name: Common Auth
    template:
      src: "templates/common-auth.j2"
      dest: "/etc/pam.d/common-auth"
      mode: 0755
      
  - name: Common Account
    template:
      src: "templates/common-account.j2"
      dest: "/etc/pam.d/common-account"
      mode: 0755
       
  - name: Common Password
    template:
      src: "templates/common-password.j2"
      dest: "/etc/pam.d/common-password"
      mode: 0755
      
  - name: Common Session
    template:
      src: "templates/common-session.j2"
      dest: "/etc/pam.d/common-session"
      mode: 0755  
 
  - name: NS Switch
    template:
      src: "templates/nsswitch.conf.j2"
      dest: "/etc/nsswitch.conf"
      mode: 0755  

  - name: Samba
    template:
      src: "templates/samba.conf.j2"
      dest: "/etc/samba/smb.conf"
      mode: 0755
      
  - name: Realmd
    template:
      src: "templates/realmd.conf.j2"
      dest: "/etc/realmd.conf"
      mode: 0755
 
  - name: JOIN Active  
    shell: net ads join -U user%password	

  - name: Start service smbd
    systemd:
      name: smbd
      state: started

  - name: Stop service winbind, if started
    systemd:
      name: winbind
      state: stopped

  - name: Restart smbd
    systemd:
      name: smbd
      state: restarted

  - name: Start service winbind if not started
    systemd:
      name: winbind
      state: started
 
  - name: Make sure the folder exists (Debian, Ubuntu)
    file:
      path: /usr/local/share/ca-certificates
      state: directory

  - name: Remove Thunderbird
    apt:
      name=thunderbird state=absent


